### PR TITLE
Created a results table and analysis function

### PR DESCRIPTION
**Pull request by Lancasterwu**
The code isn't complete. Working on it

### CODE REVIEW

**Comment by gkapfham** [comment]
Hello @huangs1 and @Lancasterwu, do you still want to keep this issue open given the fact that the build is currently failing? Can you please report back as to the best way forward?

**Comment by gkapfham** [comment]
Hello @Lancasterwu can you please give a more detailed description of how this PR will influence the master branch once it is merged? Can you give some examples of how it works correctly?

**Comment by lussierc** [comment]
@gkapfham We will add more information about this pull request's purpose and functionality today!

**Comment by Lancasterwu** [comment]
Hi @gkapfham, This PR uses package `prettytable` to create the results table and displays it in the output. The results table gets the mean, median of the experiments, and calculates the ratio by using the current mean divided by the last round mean. We still need to add features such as giving expected Big-O, analyze the results table, etc..  There are some confusions on the numbers returned by the results table because we would not get the expected Big-O by analyzing it. I'm not sure if it is a good idea to merge it right now. However, this program was tested by its test case so it would not break the code in the master branch.

**Comment by gkapfham** [comment]
Thanks for the summary @Lancasterwu! Please add more details once they are available. We should we able to show that we get the correct big-Oh for all functions or have a clear explanation for why we do not get the correct big-Oh. The details can be added to the issue tracker or to this PR. Please tell me where to look once all of the data tables are available. I look forward to seeing finalize results next week!

**Pull request merged**
